# Generated by Django 3.1.12 on 2025-05-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20250428_2133'),
        ('activitylogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogs',
            name='path',
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.course'),
        ),
    ]
