# Generated by Django 3.1.12 on 2025-05-04 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activitylogs', '0002_auto_20250504_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylogs',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
