# Generated by Django 3.1.12 on 2025-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='desc',
            new_name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
