# Generated by Django 3.1.12 on 2025-04-28 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=7)),
                ('isArchived', models.BooleanField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
